//----------------------------------------------------------------------------
// ErroresDX
//
// functions to visualize any DX error
//----------------------------------------------------------------------------

#pragma once

#define CHECKDXERROR( hr, func ) CheckDXError( hr, func, __FUNCTION__, __FILE__, true)
#define CHECKERROR_NOAS( hr, func ) CheckDXError( hr, func, __FUNCTION__, __FILE__, false)

ERetVal CheckDXError( int hr, const char* pszDXFunc, const char* pszFunc, const char* pszFile, bool bAssert );


#define F_DIRECT3DCREATE9                       "DIRECT3DCREATE9"
#define F_CREATEDEVICE                          "CREATEDEVICE"  
#define F_SETRENDERSTATE                        "SETRENDERSTATE"
#define F_SETLIGHT                              "SETLIGHT"
#define F_GETLIGHT                              "GETLIGHT"
#define F_LIGHTENABLE                           "LIGHTENABLE"
#define F_SETTRANSFORM                          "SETTRANSFORM"
#define F_GETTRANSFORM                          "GETTRANSFORM"
#define F_CLEAR                                 "CLEAR"
#define F_ENDSCENE                              "ENDSCENE"
#define F_CREATEVERTEXBUFFER                    "CREATEVERTEXBUFFER"
#define F_CREATEVERTEXDECLARATION               "CREATEVERTEXDECLARATION"
#define F_LOCK                                  "LOCK"
#define F_UNLOCK                                "UNLOCK"
#define F_CREATEINDEXBUFFER                     "CREATEINDEXBUFFER"
#define F_SETSTREAMSOURCE                       "SETSTREAMSOURCE"
#define F_SETFVF                                "SETFVF"
#define F_DRAWPRIMITIVE                         "DRAWPRIMITIVE"
#define F_SETINDICES                            "SETINDICES"
#define F_DRAWINDEXEDPRIMITIVE                  "DRAWINDEXEDPRIMITIVE"
#define F_SETMATERIAL                           "SETMATERIAL"
#define F_SETTEXTURE                            "SETTEXTURE"
#define F_CREATETEXTURE                         "CREATETEXTURE"
#define F_BEGINSCENE                            "BEGINSCENE"
#define F_PRESENT                               "PRESENT"
#define F_LOCKRECT                              "LOCKRECT"
#define F_UNLOCKRECT                            "UNLOCKRECT"
#define F_GETDEVICECAPS                         "GETDEVICECAPS"
#define F_GETLEVELDESC                          "GETLEVELDESC"
#define F_GETADAPTERDISPLAYMODE                 "GETADAPTERDISPLAYMODE"
#define F_CHECKDEVICEFORMAT                     "CHECKDEVICEFORMAT"
#define F_GETBACKBUFFER                         "GETBACKBUFFER"
#define F_RESET                                 "RESET"
#define F_GETDEPTHSTENCILSURFACE                "GETDEPTHSTENCILSURFACE"
#define F_D3DXCOMPILESHADERFROMFILE             "D3DXCOMPILESHADERFROMFILE"
#define F_CREATEVERTEXSHADER                    "CREATEVERTEXSHADER"
#define F_SETVERTEXDECLARATION                  "SETVERTEXDECLARATION"
#define F_SETVERTEXSHADER                       "SETVERTEXSHADER"
#define F_SETMATRIX                             "SETMATRIX"
#define F_SETPIXELSHADER                        "SETPIXELSHADER"
#define F_SETINT                                "SETINT"
#define F_SETFLOAT                              "SETFLOAT"
#define F_SETSAMPLERSTATE                       "SETSAMPLERSTATE"
#define F_D3DXCREATEEFFECTFROMFILE              "D3DXCREATEEFFECTFROMFILE"
#define F_BEGINPASS                             "BEGINPASS"
#define F_ENDPASS                               "ENDPASS"
#define F_BEGIN                                 "BEGIN"
#define F_SETVECTOR                             "SETVECTOR"
#define F_SETTECHNIQUE                          "SETTECHNIQUE"
#define F_DIRECTINPUT8CREATE                    "DIRECINPUT8CREATE"
#define F_SETDATAFORMAT                         "SETDATAFORMAT"
#define F_SETCOOPERATIVELEVEL                   "SETCOOPERATIVELEVL"
#define F_ACQUIRE                               "ACQUIRE"
#define F_D3DXCREATETEXTUREFROMFILEEX           "D3DXCREATETEXTUREFROMFILEEX"
#define F_GETSURFACELEVEL                       "GETSURFACELEVEL"
#define F_D3DXLOADSURFACEFROMSURFACE            "D3DXLOADSURFACEFROMSURFACE"
#define F_D3DXSAVETEXTURETOFILEINMEMORY         "D3DXSAVETEXTURETOFILEINMEMORY"
#define F_D3DXCREATETEXTUREFROMFILEINMEMORYEX   "D3DXCREATETEXTUREFROMFILEINMEMORYEX"
#define F_GETVIEWPORT                           "GETVIEWPORT"
#define F_GETRENDERTARGET                       "GETRENDERTARGET"
#define F_SETRENDERTARGET                       "SETRENDERTARGET"
#define F_SETDEPTHSTENCILSURFACE                "SETDEPTHSTENCILSURFACE"
#define F_SETVECTORARRAY                        "SETVECTORARRAY"
#define F_SETMATRIXARRAY                        "SETMATRIXARRAY"
#define F_TESTCOOPERATIVELEVEL                  "TESTCOOPERATIVELEVEL"

#define F_DIRECTSOUNDCREATE8                    "DIRECTSOUNDCREATE8"
#define F_CREATESOUNDBUFFER                     "CREATESOUNDBUFFER"
#define F_QUERYINTERFACE                        "QUERYINTERFACE"
#define F_PLAY                                  "PLAY"
#define F_SETCURRENTPOSITION                    "SETCURRENTPOSITION"
#define F_STOP                                  "STOP"
#define F_GETSTATUS                             "GETSTATUS"
#define F_SETVOLUME                             "SETVOLUME"
#define F_GETVOLUME                             "GETVOLUME"
#define F_DUPLICATESOUNDBUFFER                  "DUPLICATESOUNDBUFFER"

#define F_UNACQUIRE                             "UNACQUIRE"
#define F_GETPROPERTY                           "GETPROPERTY"
#define F_SETPROPERTY                           "SETPROPERTY"
#define F_GETDEVICEDATA                         "GETDEVICEDATA"
